Repository SlimeKnights/TinkersConstruct, pull requests merged in 2021-05, with the labels that each got.

#4348 Kama tripwire
  src/main/java/slimeknights/tconstruct/library/tools/helper/ToolHarvestLogic.java
  src/main/java/slimeknights/tconstruct/tools/harvest/KamaTool.java
Labels: 1.16, Enhancement

#4415 Right click modifier hooks
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/ancient_axe_head_gold_cast.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/ancient_axe_head_sand_cast.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/ancient_hoe_head_gold_cast.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/ancient_hoe_head_sand_cast.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/ancient_shovel_head_gold_cast.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/ancient_shovel_head_sand_cast.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/ancient_tool_heads.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/upgrade/axe_transform.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/upgrade/glowing.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/upgrade/hoe_transform.json
  src/generated/resources/data/tconstruct/recipes/tools/modifiers/upgrade/shovel_transform.json
  src/main/java/slimeknights/tconstruct/library/modifiers/Modifier.java
  src/main/java/slimeknights/tconstruct/library/tools/events/TinkerToolEvent.java
  src/main/java/slimeknights/tconstruct/library/tools/helper/ToolHarvestLogic.java
  src/main/java/slimeknights/tconstruct/library/tools/helper/aoe/CircleAOEHarvestLogic.java
  src/main/java/slimeknights/tconstruct/library/tools/helper/aoe/DepthAOEHarvestLogic.java
  src/main/java/slimeknights/tconstruct/library/tools/helper/aoe/RectangleAOEHarvestLogic.java
  src/main/java/slimeknights/tconstruct/library/tools/helper/aoe/TreeAOEHarvestLogic.java
  src/main/java/slimeknights/tconstruct/library/tools/helper/aoe/VeiningAOEHarvestLogic.java
  src/main/java/slimeknights/tconstruct/library/tools/item/SwordCore.java
  src/main/java/slimeknights/tconstruct/library/tools/item/ToolCore.java
  src/main/java/slimeknights/tconstruct/tools/TinkerModifiers.java
  src/main/java/slimeknights/tconstruct/tools/ToolDefinitions.java
  src/main/java/slimeknights/tconstruct/tools/data/ModifierRecipeProvider.java
  src/main/java/slimeknights/tconstruct/tools/harvest/HandAxeTool.java
  src/main/java/slimeknights/tconstruct/tools/harvest/HarvestTool.java
  src/main/java/slimeknights/tconstruct/tools/harvest/KamaTool.java
  src/main/java/slimeknights/tconstruct/tools/harvest/MattockTool.java
  src/main/java/slimeknights/tconstruct/tools/harvest/PickaxeTool.java
  src/main/java/slimeknights/tconstruct/tools/harvest/broad/BroadAxeTool.java
  src/main/java/slimeknights/tconstruct/tools/harvest/broad/ExcavatorTool.java
  src/main/java/slimeknights/tconstruct/tools/harvest/broad/ScytheTool.java
  src/main/java/slimeknights/tconstruct/tools/harvest/broad/VeinHammerTool.java
  src/main/java/slimeknights/tconstruct/tools/melee/CleaverTool.java
  src/main/java/slimeknights/tconstruct/tools/modifiers/ability/BlockTransformModifier.java
  src/main/java/slimeknights/tconstruct/tools/modifiers/ability/GlowingModifier.java
  src/main/java/slimeknights/tconstruct/tools/modifiers/ability/HarvestAbilityModifier.java
  src/main/java/slimeknights/tconstruct/tools/modifiers/ability/ShearsAbilityModifier.java
  src/main/java/slimeknights/tconstruct/tools/modifiers/ability/SilkyShearsAbilityModifier.java
  src/main/java/slimeknights/tconstruct/tools/modifiers/ability/TwoHandedAbilityModifier.java
  src/main/resources/assets/tconstruct/lang/en_us.json
  src/main/resources/assets/tconstruct/models/item/ancient_axe_head.json
  src/main/resources/assets/tconstruct/models/item/ancient_hoe_head.json
  src/main/resources/assets/tconstruct/models/item/ancient_shovel_head.json
  src/main/resources/assets/tconstruct/textures/item/ancient_axe_head.png
  src/main/resources/assets/tconstruct/textures/item/ancient_hoe_head.png
  src/main/resources/assets/tconstruct/textures/item/ancient_shovel_head.png
Labels: 1.16, Feature, TiC Api

#4483 new textures for tinkers bronze, knightslime, soulsteel and hollow
  src/main/resources/assets/tconstruct/models/block/table/tinkers_anvil.json
  src/main/resources/assets/tconstruct/models/block/template/faucet.json
  src/main/resources/assets/tconstruct/models/block/template/faucet_up.json
  src/main/resources/assets/tconstruct/textures/block/fluid/soul/flowing.png
  src/main/resources/assets/tconstruct/textures/block/fluid/soul/flowing.png.mcmeta
  src/main/resources/assets/tconstruct/textures/block/fluid/soul/still.png
  src/main/resources/assets/tconstruct/textures/block/fluid/soul/still.png.mcmeta
  src/main/resources/assets/tconstruct/textures/block/fluid/soulsteel/flowing.png
  src/main/resources/assets/tconstruct/textures/block/fluid/soulsteel/flowing.png.mcmeta
  src/main/resources/assets/tconstruct/textures/block/fluid/soulsteel/still.png
  src/main/resources/assets/tconstruct/textures/block/fluid/soulsteel/still.png.mcmeta
  src/main/resources/assets/tconstruct/textures/block/storage/hollow.png
  src/main/resources/assets/tconstruct/textures/block/storage/knightslime.png
  src/main/resources/assets/tconstruct/textures/block/storage/soulsteel.png
  src/main/resources/assets/tconstruct/textures/block/storage/tinkers_bronze.png
  src/main/resources/assets/tconstruct/textures/block/table/anvil_base.png
  src/main/resources/assets/tconstruct/textures/block/table/anvil_base_upper.png
  src/main/resources/assets/tconstruct/textures/item/materials/hollow_dust.png
  src/main/resources/assets/tconstruct/textures/item/materials/hollow_gem.png
  src/main/resources/assets/tconstruct/textures/item/materials/hollow_ingot.png
  src/main/resources/assets/tconstruct/textures/item/materials/hollow_nugget.png
  src/main/resources/assets/tconstruct/textures/item/materials/hollow_pearl.png
  src/main/resources/assets/tconstruct/textures/item/materials/hollow_rod.png
  src/main/resources/assets/tconstruct/textures/item/materials/knightslime_ingot.png
  src/main/resources/assets/tconstruct/textures/item/materials/knightslime_nugget.png
  src/main/resources/assets/tconstruct/textures/item/materials/soulsteel_ingot.png
  src/main/resources/assets/tconstruct/textures/item/materials/soulsteel_nugget.png
  src/main/resources/assets/tconstruct/textures/item/materials/tinkers_bronze_ingot.png
  src/main/resources/assets/tconstruct/textures/item/materials/tinkers_bronze_nugget.png
Labels: 1.16, Textures

#4352 Add CraftTweaker support
  build.gradle
  gradle.properties
  src/main/java/slimeknights/tconstruct/TConstruct.java
  src/main/java/slimeknights/tconstruct/library/recipe/melting/DamageableMeltingRecipe.java
  src/main/java/slimeknights/tconstruct/plugin/crt/CRTHelper.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/AlloyingManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/BeheadingManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/CastingBasinManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/CastingTableManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/EntityMeltingManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/FuelManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/MaterialRecipeManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/MeltingManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/MoldingBasinManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/MoldingTableManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/PartBuilderManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/TinkerStationManager.java
  src/main/java/slimeknights/tconstruct/plugin/crt/managers/base/ICastingManager.java
  src/main/java/slimeknights/tconstruct/smeltery/TinkerSmeltery.java
  src/main/resources/META-INF/mods.toml
  src/main/resources/data/tconstruct/scripts/tconstruct/alloying.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/beheading.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/casting_basin.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/casting_table.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/entity_melting.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/fuel.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/material_recipe.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/melting.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/molding_basin.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/molding_table.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/part_builder.zs
  src/main/resources/data/tconstruct/scripts/tconstruct/tinker_station.zs
Labels: 1.16, Feature
