Repository SlimeKnights/TinkersConstruct, pull requests merged in 2022-12, with the labels that each got.

#4998 Bug fixes in translation area.
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/abilities/interact/pathing.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/abilities/interact/stripping.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/abilities/interact/tilling.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/abilities/weapon/dual_wielding.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/armor/slime/skull.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/defense/protection/melee.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/slotless/general/overslime.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/small_tools/info.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/upgrades/general/diamond.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/upgrades/general/emerald.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/upgrades/general/magnetic.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/upgrades/general/netherite.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/upgrades/general/offhanded.json
  src/main/resources/assets/tconstruct/book/encyclopedia/pt_br/upgrades/general/tank.json
  src/main/resources/assets/tconstruct/book/encyclopedia/ru_ru/abilities/weapon/dual_wielding.json
  src/main/resources/assets/tconstruct/book/fantastic_foundry/pt_br/armor/chestplate.json
  src/main/resources/assets/tconstruct/book/materials_and_you/ko_kr/tools/kama.json
  src/main/resources/assets/tconstruct/book/materials_and_you/ru_ru/tools/kama.json
  src/main/resources/assets/tconstruct/book/mighty_smelting/ko_kr/abilities/interact/bucketing.json
  src/main/resources/assets/tconstruct/book/puny_smelting/ko_kr/upgrades/weapon/sticky.json
  src/main/resources/assets/tconstruct/book/puny_smelting/pt_br/upgrades/harvest/haste.json
  src/main/resources/assets/tconstruct/book/puny_smelting/pt_br/upgrades/weapon/sticky.json
  src/main/resources/assets/tconstruct/book/puny_smelting/ru_ru/upgrades/weapon/sticky.json
  src/main/resources/assets/tconstruct/lang/pt_br.json
  src/main/resources/assets/tconstruct/lang/uk_ua.json
Labels: Technical, 1.18

#5043 Implement block transform modifier hook
  src/main/java/slimeknights/tconstruct/library/modifiers/TinkerHooks.java
  src/main/java/slimeknights/tconstruct/library/modifiers/hook/BlockTransformModifierHook.java
  src/main/java/slimeknights/tconstruct/tools/modifiers/ability/interaction/BlockTransformModifier.java
Labels: Feature, Needs Update, 1.18

#5011 Update ja_jp.json
  src/main/resources/assets/tconstruct/lang/ja_jp.json
Labels: Translation, 1.18
